# "image": "linuxserver/snapdrop:latest"
# inkscape -w 128 -h 128 snapdrop.svg -o icon.png
# "C:\Program Files\Inkscape\bin\inkscape" -w 128 -h 128 snapdrop.svg -o icon.png

FROM linuxserver/snapdrop:latest
